### ISSUE TITLE
Live update of position column on reordering

### ISSUE THREAD

**Issue by yurii-holenko** [dkniffin/activeadmin_reorderable#21]
Add live reload of position value after no error thrown

**Comment by dkniffin** [comment]
@yurii-holenko can you explain this a bit further? I don't think I understand.

**Comment by yurii-holenko** [comment]
If you put position column on index page you will see that value doesn't updates after drop. My proposal is to handle this case on frontend. Something like callback after successful request.

**Comment by dkniffin** [comment]
@yurii-holenko I'm sorry it took me so long to discover this, but the gem already supports this functionality [here](https://github.com/dkniffin/activeadmin_reorderable/blob/81ba02a18d30710cf38db74244a98bfa3430c981/app/assets/javascripts/activeadmin_reorderable.js#L45). All you have to do is add a `position` class to the column (eg `column :position, class: "position"`)
