### ISSUE TITLE
0.3.0 JS issue

### ISSUE THREAD

**Issue by dramalho** [dkniffin/activeadmin_reorderable#28]
Hi :)

We were testing the upgrade to the 0.3.0 version and we're hitting a snag, it looks like an actual but but I wanted to run by you.

The short version is:

* Browser complains about `Cannot read properties of undefined (reading '0') / at HTMLTableRowElement.<anonymous> (activeadmin_reorderable.source.js:33:1)`
* I added a debugger and the reason why is because it's trying to call [`tBodies` on a `div` , not a `table`](https://github.com/dkniffin/activeadmin_reorderable/blob/df318103d3a835f8d5717194ebbda4c06a8d87ce/app/assets/javascripts/activeadmin_reorderable.js#L33)
* The reason why is because it's calling `setupReorderableTable` by [looking for elements with the `aa-reorderable` class](https://github.com/dkniffin/activeadmin_reorderable/blob/df318103d3a835f8d5717194ebbda4c06a8d87ce/app/assets/javascripts/activeadmin_reorderable.js#L82) and in `index as: :reorderable_table` pages both the div and table have the class
* The reason why is because (I assume) both [index](https://github.com/dkniffin/activeadmin_reorderable/blob/df318103d3a835f8d5717194ebbda4c06a8d87ce/lib/active_admin/views/index_as_reorderable_table.rb#L10) and [table](https://github.com/dkniffin/activeadmin_reorderable/blob/master/lib/active_admin/views/reorderable_table_for.rb#L7) end up adding the same class

Assuming I didn't miss a beat, I guess either adding the class onto the table or, probably more to the point, making sure the `table`  element is targeted explicitly is the fix.

Either way, kinda weird, I'm unsure if we're doing something wrong

**Comment by dkniffin** [comment]
@dramalho Interesting. Thank you for reporting and investigating. In my testing, I hadn't tested the `index as: :reorderable_table` version.

I'll add that to the test suite now and change the `querySelectorAll(".aa-reorderable")` to `querySelectorAll("table.aa-reorderable")` and see if that resolves it. If it does, I'll push a patch version w/ the fix

**Comment by dramalho** [comment]
Yeah, that should fix it, it's really just a specific JS issue, I just wanted to run it by you in case I was missing something *super obvious* 

thank you Derek 🫶

**Comment by dkniffin** [comment]
@dramalho I fixed it and pushed a v0.3.1. Can you test it and let me know if it resolves the issue for you?

**Comment by dramalho** [comment]
ok, re: the original issue, it's great, things are working again but -- I am noticing something new though :)  (sorry man, I know this is annoying)

So, if I drag (but don't release the button, or don't release it quick enough) I notice it gets stuck in a look on that `dragover` handler and keeps swapping lines very quickly, each time initiating a `reorder` request

<img width="1353" alt="image" src="https://github.com/user-attachments/assets/419eb161-355b-464b-aaea-881a6b450dcf">

Unsure if the actual network request should be done at `dragend` ?

**Comment by dramalho** [comment]
this is a new issue though, want me to open a new one?

**Comment by dramalho** [comment]
(in the meantime let me try on safari - this was chrome)

**Comment by dramalho** [comment]
ahh the wonderful world of frontend dev, safari / firefox are fine, chrome is doing machine gun requests 😭

**Comment by dramalho** [comment]
Ok, kinda hard to replicate but I get the same behaviour in Safari as well -- best bet is horizontal size, especially when the index table that AA generates starts to get compressed (< 900px for this particular screen I'm looking at) -- the rows start to flip between each other and because the network request is there (and not when we release the button) it machine guns the server

I know the previous version only acted on the drag when we released the row, one option might be to update the UI on `dragover` but shoot the network request on `dragend` ?

**Comment by dkniffin** [comment]
Ah yeah.... 🤦  I meant to switch the POST request to `dragend` but forgot. I think it's actually bad UX as-is and the change should only apply when the mouse button is released.

I'll work on that soon.

**Comment by dkniffin** [comment]
@dramalho Done. Give 0.3.2 a try

**Comment by dramalho** [comment]
Third time's a charm!!! I'll test it now 👏

**Comment by dramalho** [comment]
looks good, the UI still does the little bit where if the horizontal size is small enough and I drag the lines *just* slightly it starts to endlessly swap rows, but as no network requests are generated this is less of a problem

I'll push this to production, thaaaaaaaaaaaaank you Derek ❤️
