### ISSUE TITLE
Support webpacker / Rails 6

### ISSUE THREAD

**Issue by dkniffin** [dkniffin/activeadmin_reorderable#8]
Rails 6 requires webpacker. [AA supports webpacker now](https://github.com/activeadmin/activeadmin/issues/5558#issuecomment-622335752), but in order for this gem to work on Rails 6, it needs an npm equivalent.

**Comment by kwent** [comment]
Agreed. Is this library still maintained?

**Comment by dkniffin** [comment]
An update here: I got this repo transferred over to me and I'll be maintaining it now. I'll take care of this issue soon (in the next month or so), as well as reviewing the other open issues and PRs.

**Comment by kwent** [comment]
@dkniffin  This is amazing !! Thank you

**Comment by sergewhite** [comment]
@dkniffin Any updates so far?

**Comment by dkniffin** [comment]
I'm so sorry. I still haven't found the time to do this. We use this at my day job, and at the time we were working on upgrading AA to webpacker and this was a blocker, but since then it got deprioritized. I will try my best to find some after-hours time to take care of this.

**Comment by dkniffin** [comment]
Webpacker / npm support has been added in v0.2.0. The readme contains instructions on how to use it.
